In [179]:
import os

print(os.getcwd())

c:\MY ALL\Analytics Study\Project\Ecommerce Data Pipeline\Notebooks

In [180]:
import os

raw_path = "../data/raw"

print(os.listdir(raw_path))

['olist_customers_dataset.csv', 'olist_geolocation_dataset.csv', 'olist_orders_dataset.csv', 'olist_order_items_dataset.csv', 'olist_order_payments_dataset.csv', 'olist_order_reviews_dataset.csv', 'olist_products_dataset.csv', 'olist_sellers_dataset.csv', 'product_category_name_translation.csv']

In [181]:
import pandas as pd

customers = pd.read_csv("../data/raw/olist_customers_dataset.csv")

customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [182]:
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

In [183]:
customers.shape

(99441, 5)

In [184]:
customers.dtypes

customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

In [185]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [186]:
customers.duplicated().sum()

np.int64(0)

## starting second csv inspection

In [187]:
geolocation = pd.read_csv("../data/raw/olist_geolocation_dataset.csv")

In [188]:
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [189]:
geolocation.shape

(1000163, 5)

In [190]:
geolocation.columns

Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='str')

In [191]:
geolocation.dtypes

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

In [192]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [193]:
geolocation.duplicated().sum()

np.int64(261831)

#### FILE 3

In [194]:
orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")

In [195]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [196]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [197]:
orders.shape

(99441, 8)

In [198]:
orders.dtypes

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [199]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [200]:
orders.duplicated().sum()

np.int64(0)

## file 4

In [201]:
order_items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")

In [202]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [203]:
order_items.shape

(112650, 7)

In [204]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')

In [205]:
order_items.dtypes

order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

In [206]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [207]:
order_items.duplicated().sum()

np.int64(0)

In [208]:
order_payments = pd.read_csv("../data/raw/olist_order_payments_dataset.csv")

In [209]:
order_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [210]:
order_payments.shape

(103886, 5)

In [211]:
order_payments.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='str')

In [212]:
order_payments.dtypes

order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

In [213]:
order_payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [214]:
order_payments.duplicated().sum()

np.int64(0)

## FILE 6

In [215]:
order_reviews = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")

In [216]:
order_reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [217]:
order_reviews.shape

(99224, 7)

In [218]:
order_reviews.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='str')

In [219]:
order_reviews.dtypes

review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

In [220]:
order_reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [221]:
order_reviews.duplicated().sum()

np.int64(0)

## FILE 7

In [222]:
products = pd.read_csv("../data/raw/olist_products_dataset.csv")

In [223]:
products.head( )

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [224]:
products.shape

(32951, 9)

In [225]:
products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')

In [226]:
products.dtypes

product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [227]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [228]:
products.duplicated().sum()

np.int64(0)

### FILE 8

In [229]:
sellers = pd.read_csv("../data/raw/olist_sellers_dataset.csv")

In [230]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [231]:
sellers.shape

(3095, 4)

In [232]:
sellers.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='str')

In [233]:
sellers.dtypes

seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

In [234]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [235]:
sellers.duplicated().sum()

np.int64(0)

## FILE 9

In [236]:
category_translation = pd.read_csv(
    "../data/raw/product_category_name_translation.csv"
)

In [237]:
category_translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [238]:
category_translation.shape

(71, 2)

In [239]:
category_translation.columns

Index(['product_category_name', 'product_category_name_english'], dtype='str')

In [240]:
category_translation.dtypes

product_category_name            str
product_category_name_english    str
dtype: object

In [241]:
category_translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [242]:
category_translation.duplicated().sum()

np.int64(0)




###### DATA RELATION CHECK

In [243]:
# from this and next code we will verify whether the no of rows have the unqiue values or not
# if these value are equal then each row have a unqiue customer

customers["customer_id"].nunique()

99441

In [244]:
len(customers)

99441

In [245]:
orders["customer_id"].nunique()

99441

In [246]:
orders["customer_id"].duplicated().sum()

np.int64(0)

In [247]:
order_items["order_id"].nunique()

98666

In [248]:
order_items["order_id"].duplicated().sum()

np.int64(13984)

In [249]:
order_items["product_id"].nunique()

32951

In [250]:
order_items["product_id"].isin(products["product_id"]).all()

np.True_

In [251]:
order_items["seller_id"].isin(sellers["seller_id"]).all()

np.True_

In [252]:
order_payments["order_id"].isin(orders["order_id"]).all()

np.True_

In [253]:
order_payments["order_id"].duplicated().sum()

np.int64(4446)

In [254]:
order_reviews["order_id"].isin(orders["order_id"]).all()

np.True_

In [255]:
order_reviews["order_id"].duplicated().sum()

np.int64(551)

In [256]:
products["product_category_name"].dropna().isin(
    category_translation["product_category_name"]
).all()

np.False_

In [257]:
(~products["product_category_name"].dropna().isin(
    category_translation["product_category_name"]
)).sum()

np.int64(13)

### finding which product category name have no translation

In [258]:
missing_categories = ~products["product_category_name"].isin(
    category_translation["product_category_name"]
)

In [259]:
missing_categories = missing_categories & products["product_category_name"].notna()

In [260]:
products.loc[missing_categories, "product_category_name"].unique()

<StringArray>
['pc_gamer', 'portateis_cozinha_e_preparadores_de_alimentos']
Length: 2, dtype: str

In [261]:
products.loc[missing_categories, "product_category_name"].value_counts()

product_category_name
portateis_cozinha_e_preparadores_de_alimentos    10
pc_gamer                                          3
Name: count, dtype: int64

In [262]:
orders["customer_id"].isin(customers["customer_id"]).all()

np.True_

In [263]:
products["product_id"].isin(order_items["product_id"]).all().sum()

np.int64(1)

In [264]:
order_items["product_id"].duplicated().sum()

np.int64(79699)

In [265]:
for name, df in {
    "orders": orders,
    "order_items": order_items,
    "order_reviews": order_reviews
}.items():
    print(f"\n{name}")
    print(df.columns[df.columns.str.contains("date|timestamp", case=False)].tolist())

orders
['order_purchase_timestamp', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

order_items
['shipping_limit_date']

order_reviews
['review_creation_date', 'review_answer_timestamp']

In [266]:
orders["order_purchase_timestamp"] = pd.to_datetime(
    orders["order_purchase_timestamp"]
)

In [267]:
date_cols = [
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_cols:
    orders[col] = pd.to_datetime(orders[col])

In [268]:
orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [269]:
order_items["shipping_limit_date"] = pd.to_datetime(
    order_items["shipping_limit_date"]
)

In [270]:
review_date_cols = [
    "review_creation_date",
    "review_answer_timestamp"
]

for col in review_date_cols:
    order_reviews[col] = pd.to_datetime(order_reviews[col])

In [271]:
order_items.dtypes

order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
dtype: object

In [272]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [273]:
orders.groupby("order_status")[
    [
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date"
    ]
].apply(lambda x: x.isnull().sum())

,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
order_status,,,
approved,0,2,2
canceled,141,550,619
created,5,5,5
delivered,14,2,8
invoiced,0,314,314
processing,0,301,301
shipped,0,0,1107
unavailable,0,609,609

In [274]:
orders.loc[
    (orders["order_status"] == "delivered") &
    (
        orders[
            [
                "order_approved_at",
                "order_delivered_carrier_date",
                "order_delivered_customer_date"
            ]
        ].isnull().any(axis=1)
    ),
    [
        "order_id",
        "order_status",
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ]
]

,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaT,2017-12-18
5323,e04abd8149ef81b95221e88f6ed9ab6a,delivered,2017-02-18 14:40:00,NaT,2017-02-23 12:04:47,2017-03-01 13:25:33,2017-03-17
16567,8a9adc69528e1001fc68dd0aaebbb54a,delivered,2017-02-18 12:45:31,NaT,2017-02-23 09:01:52,2017-03-02 10:05:06,2017-03-21
19031,7013bcfc1c97fe719a7b5e05e61c12db,delivered,2017-02-18 13:29:47,NaT,2017-02-22 16:25:25,2017-03-01 08:07:38,2017-03-17
20618,f5dd62b788049ad9fc0526e3ad11a097,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaT,2018-07-16
22663,5cf925b116421afa85ee25e99b4c34fb,delivered,2017-02-18 16:48:35,NaT,2017-02-22 11:23:10,2017-03-09 07:28:47,2017-03-31
23156,12a95a3c06dbaec84bcfb0e2da5d228a,delivered,2017-02-17 13:05:55,NaT,2017-02-22 11:23:11,2017-03-02 11:09:19,2017-03-20
26800,c1d4211b3dae76144deccd6c74144a88,delivered,2017-01-19 12:48:08,NaT,2017-01-25 14:56:50,2017-01-30 18:16:01,2017-03-01
38290,d69e5d356402adc8cf17e08b5033acfb,delivered,2017-02-19 01:28:47,NaT,2017-02-23 03:11:48,2017-03-02 03:41:58,2017-03-27
39334,d77031d6a3c8a52f019764e68f211c69,delivered,2017-02-18 11:04:19,NaT,2017-02-23 07:23:36,2017-03-02 16:15:23,2017-03-22
43834,2ebdfc4f15f23b91474edf87475f108e,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaT,2018-07-30
48401,7002a78c79c519ac54022d4f8a65e6e8,delivered,2017-01-19 22:26:59,NaT,2017-01-27 11:08:05,2017-02-06 14:22:19,2017-03-16
61743,2eecb0d85f281280f79fa00f9cec1a95,delivered,2017-02-17 17:21:55,NaT,2017-02-22 11:42:51,2017-03-03 12:16:03,2017-03-20
63052,51eb2eebd5d76a24625b31c33dd41449,delivered,2017-02-18 15:52:27,NaT,2017-02-23 03:09:14,2017-03-07 13:57:47,2017-03-29
67697,88083e8f64d95b932164187484d90212,delivered,2017-02-18 22:49:19,NaT,2017-02-22 11:31:06,2017-03-02 12:06:06,2017-03-21
72407,3c0b8706b065f9919d0505d3b3343881,delivered,2017-02-17 15:53:27,NaT,2017-02-22 11:31:30,2017-03-03 11:47:47,2017-03-23
73222,2aa91108853cecb43c84a5dc5b277475,delivered,2017-09-29 08:52:58,2017-09-29 09:07:16,NaT,2017-11-20 19:44:47,2017-11-14
79263,e69f75a717d64fc5ecdfae42b2e8e086,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaT,2018-07-24
84999,2babbb4b15e6d2dfe95e2de765c97bce,delivered,2017-02-18 17:15:03,NaT,2017-02-22 11:23:11,2017-03-03 18:43:43,2017-03-31
92643,2d858f451373b04fb5c984a1cc2defaf,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaT,NaT,2017-06-23
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaT,2018-07-19

In [275]:
products[products.isnull().any(axis=1)].shape

(611, 9)

In [276]:
products.loc[
    products.isnull().any(axis=1),
    ["product_id", "product_category_name", "product_name_lenght",
     "product_description_lenght", "product_photos_qty",
     "product_weight_g", "product_length_cm",
     "product_height_cm", "product_width_cm"]
]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

In [277]:
products.loc[
    products[
        ["product_weight_g",
         "product_length_cm",
         "product_height_cm",
         "product_width_cm"]
    ].isnull().any(axis=1)
]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [278]:
missing_product_ids = products.loc[
    products.isnull().any(axis=1),
    "product_id"
]

order_items["product_id"].isin(missing_product_ids).sum()

np.int64(1604)

In [279]:
order_items.loc[
    order_items["product_id"].isin(missing_product_ids),
    "product_id"
].nunique()

611

In [280]:
products.loc[
    products.isnull().any(axis=1)
].isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [281]:
products.loc[
    products["product_category_name"].isna()
].isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                1
product_length_cm               1
product_height_cm               1
product_width_cm                1
dtype: int64

In [282]:
products_with_missing_dimensions = products.loc[
    products[
        ["product_weight_g",
         "product_length_cm",
         "product_height_cm",
         "product_width_cm"]
    ].isnull().any(axis=1),
    "product_id"
]

order_items[
    order_items["product_id"].isin(products_with_missing_dimensions)
]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
7098,101157d4fae1c9fb74a00a5dee265c25,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-11 08:02:26,29.0,14.52
9233,1521c6bb7b1028154c8c67cf80fa809f,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-07 10:10:16,29.0,16.05
28715,415cfaaaa8cea49f934470548797fed1,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-07 10:35:19,29.0,14.52
28716,415cfaaaa8cea49f934470548797fed1,2,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-07 10:35:19,29.0,14.52
39299,595316a07cd3dea9db7adfcc7e247ae7,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-08-18 04:26:04,39.0,9.27
48424,6e150190fbe04c642a9cf0b80d83ee16,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-06-30 16:45:14,39.0,16.79
48980,6f497c40431d5fb0cfbd6c943dd29215,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-11 05:55:32,29.0,10.96
58833,85f8ad45e067abd694b627859fa57453,1,09ff539a621711667c43eba6a3bd8466,8b8cfc8305aa441e4239358c9f6f2485,2017-02-03 21:40:02,1934.0,27.00
71134,a2456e7f02197951664897a94c87242d,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-06 11:50:09,29.0,24.84
73556,a7a43f469c0d7bdb0a23a82db125aefa,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-08-28 13:15:11,39.0,15.10
82767,bbfc7badbed2f1828e22b6d629201bd4,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-07-18 04:04:10,39.0,11.85
84199,bf49f84a0580ef6751e13357776b7ed9,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-07-09 21:35:18,39.0,15.10
85060,c1424efcde3c9e9febd9e1761667789e,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-14 02:45:36,29.0,14.52
93346,d38dcb503cd4ddc6ce7702552918bd8f,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-06-09 17:55:13,39.0,15.10
93347,d38dcb503cd4ddc6ce7702552918bd8f,2,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-06-09 17:55:13,39.0,15.10
97847,ddf16d77e858a32f36e10c289a28ef61,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-05-02 10:50:08,29.0,14.52
100495,e3daea0200104991cb979c2fcc509ae7,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-06 14:22:36,29.0,10.96
103715,eb855beb3ac99461f7a076b4c3652472,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-03-30 16:03:46,29.0,14.52

In [283]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [284]:
geolocation.duplicated().sum()

np.int64(261831)

In [285]:
geolocation.drop_duplicates().shape

(738332, 5)

In [286]:
geolocation = geolocation.drop_duplicates()

In [287]:
geolocation.shape
geolocation.duplicated().sum()

np.int64(0)

In [288]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [289]:
orders["order_status"].unique()

<StringArray>
[  'delivered',    'invoiced',     'shipped',  'processing', 'unavailable',
    'canceled',     'created',    'approved']
Length: 8, dtype: str

In [290]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [291]:
(orders["order_approved_at"] < orders["order_purchase_timestamp"]).sum()

np.int64(0)

In [292]:
(
    orders["order_delivered_customer_date"]
    < orders["order_delivered_carrier_date"]
).sum()

np.int64(23)

In [293]:
orders.loc[
    orders["order_delivered_customer_date"]
    < orders["order_delivered_carrier_date"],
    [
        "order_id",
        "order_status",
        "order_delivered_carrier_date",
        "order_delivered_customer_date"
    ]
]

,order_id,order_status,order_delivered_carrier_date,order_delivered_customer_date
6437,a1abeb653a4d4cd1e142ccb8c82cd069,delivered,2017-07-28 16:57:58,2017-07-25 19:32:56
9553,383aa8b2724fe452d9ccd9934a8c628b,delivered,2017-07-07 17:22:41,2017-07-06 14:27:51
13487,cb1134f9010d242e9515ad1c78ec0c39,delivered,2017-07-20 19:22:02,2017-07-19 14:13:28
14474,dceb62e8fa94b46006c9554fed743df0,delivered,2017-08-01 18:23:30,2017-07-26 18:09:10
19268,5f9d46795c3126674e52becb3a1a517f,delivered,2017-07-20 23:03:42,2017-07-20 18:52:41
21338,8c78d01de3a9009e23d6877a7cc9be20,delivered,2016-10-26 11:41:53,2016-10-25 17:51:46
22520,b27af682321527a6349f1761eb3f360c,delivered,2017-06-27 14:51:54,2017-06-26 15:45:35
25393,1cc3ae63caffff2d6c3ee3e78e074acf,delivered,2017-08-10 18:28:56,2017-08-10 18:05:38
25646,e37f11cae9985ca58f0b56f268720537,delivered,2017-08-01 18:17:47,2017-07-31 17:49:56
27470,fa3e37584f4fdb1ded0e0de700dfcb4e,delivered,2017-08-09 18:18:43,2017-08-01 21:13:01
34939,c1e2bf2b7dd3309f2f5356c6b63968fa,delivered,2017-03-02 17:34:26,2017-02-14 15:15:57
41636,b866af202be0692766081310cd4085e1,delivered,2017-02-20 02:32:08,2017-02-15 03:53:46
45302,29941903985f944b0ffc49c479c1547d,delivered,2017-06-09 15:07:29,2017-06-02 11:09:16
49933,76458889992169d3135b264dc13aec67,delivered,2016-10-26 11:43:06,2016-10-20 18:03:17
50373,0922ee1619de7b995648e5a8407afb91,delivered,2017-07-14 12:41:34,2017-07-12 20:49:42
58428,fbffbaaa30f4077e87ec6acdb835b278,delivered,2017-08-04 20:04:17,2017-08-03 20:30:00
68312,3ee6694bb99d5a6db0deceffcd099597,delivered,2017-07-11 18:15:40,2017-07-11 17:41:26
71227,19feb5627c41ea1b36a8e50a469b3644,delivered,2016-10-26 11:42:05,2016-10-20 19:07:54
74967,d5558a097766363b8e76b38c43332e8a,delivered,2017-02-15 08:55:26,2017-02-10 07:58:32
76120,771c4f1f521f462e4b95619e648aaeab,delivered,2017-03-30 13:14:34,2017-03-28 17:28:32
78556,ea1dcb4757a844d2642547797bd5feb0,delivered,2017-07-27 19:21:31,2017-07-25 19:43:10
90373,99ad48402644a3968f2481defdc57947,delivered,2017-08-12 00:03:35,2017-08-10 21:22:31
95634,f688669f48063536e082bb32d634cd46,delivered,2016-10-21 18:02:40,2016-10-20 20:33:27

In [294]:
(
    orders["order_delivered_customer_date"]
    < orders["order_purchase_timestamp"]
).sum()

np.int64(0)

In [295]:
(
    orders["order_estimated_delivery_date"]
    < orders["order_purchase_timestamp"]
).sum()

np.int64(0)

In [296]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [297]:
order_items["order_item_id"].value_counts()

# for each order id we can have orders with multiple items so inside an order having multiple items
# we give each item a unqiue id 

# order_id    order_item_id
# A           1
# A           2
# A           3
# B           1
# B           2
# C           1

# A have 3 order items eaching having different ids
# hence this result tell us there 98666 order which have atleast 1 item, 9803 order having 2 orders

order_item_id
1     98666
2      9803
3      2287
4       965
5       460
6       256
7        58
8        36
9        28
10       25
11       17
12       13
13        8
14        7
15        5
16        3
17        3
18        3
19        3
20        3
21        1
Name: count, dtype: int64

In [298]:
order_items.duplicated(
    subset=["order_id", "order_item_id"]
).sum()

np.int64(0)

In [299]:
order_items["product_id"].isin(products["product_id"]).all()

np.True_

In [300]:
order_items["seller_id"].isin(sellers["seller_id"]).all()

np.True_

In [301]:
(order_items["price"] < 0).sum()

np.int64(0)

In [302]:
(order_items["freight_value"] < 0).sum()

np.int64(0)

In [303]:
order_items_check = order_items.merge(
    orders[["order_id", "order_purchase_timestamp"]],
    on="order_id",
    how="left"
)

# when we do merge, pandas uses the common column to merge and keep that only once,

In [304]:
(
    order_items_check["shipping_limit_date"]
    < order_items_check["order_purchase_timestamp"]
).sum()

np.int64(0)

In [305]:
order_payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [306]:
order_payments["payment_type"].unique()

<StringArray>
['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined']
Length: 5, dtype: str

In [307]:
order_payments["payment_type"].value_counts()


# value count gives us count of rows for each payment types

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [308]:
order_payments.loc[
    order_payments["payment_type"] == "not_defined"
]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0

In [309]:
(order_payments["payment_installments"] < 1).sum()

np.int64(2)

In [310]:
order_payments.loc[
    order_payments["payment_installments"] < 1
]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [311]:
order_payments.loc[
    order_payments["order_id"].isin([
        "744bade1fcf9ff3f31d860ace076d422",
        "1a57108394169c0b47d8f876acc9ba2d"
    ])
]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [312]:
orders.loc[
    orders["order_id"].isin([
        "744bade1fcf9ff3f31d860ace076d422",
        "1a57108394169c0b47d8f876acc9ba2d"
    ])
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
63782,744bade1fcf9ff3f31d860ace076d422,5e5794daaa13f73e2f1cdb4114529843,delivered,2018-04-22 11:34:42,2018-04-24 19:04:46,2018-04-24 03:14:34,2018-04-27 20:55:28,2018-05-16
66368,1a57108394169c0b47d8f876acc9ba2d,48ebb06cf56dba9d009230cc751bb195,delivered,2018-05-15 16:25:14,2018-05-15 16:36:52,2018-05-17 12:37:00,2018-05-24 15:45:41,2018-06-06

In [313]:
(order_payments["payment_value"] < 0).sum()

np.int64(0)

In [314]:
order_items["item_total"] = (
    order_items["price"] + order_items["freight_value"]
)

In [315]:
order_totals = (
    order_items
    .groupby("order_id")["item_total"]
    .sum()
    .reset_index()
)

In [316]:
order_totals.head()

                           order_id  item_total
0  00010242fe8c5a6d1ba2dd792cb16214       72.19
1  00018f77f2f0320c557190d7a144bdd3      259.83
2  000229ec398224ef6ca0657da4fc703e      216.87
3  00024acbcdf0a6daa1e931b038114c75       25.78
4  00042b26cf59d7ce69dfabb4e55b4fd9      218.04

In [317]:
payment_totals = (
    order_payments
    .groupby("order_id")["payment_value"]
    .sum()
    .reset_index()
)

In [318]:
order_payment_check = order_totals.merge(
    payment_totals,
    on="order_id",
    how="inner"
)

In [319]:
order_payment_check["difference"] = (
    order_payment_check["item_total"]
    - order_payment_check["payment_value"]
)

In [320]:
(order_payment_check["difference"] != 0).sum()

np.int64(19737)

In [321]:
order_payment_check.loc[
    order_payment_check["difference"] != 0,
    ["order_id", "item_total", "payment_value", "difference"]
].head(10)

                            order_id  item_total  payment_value    difference
4   00042b26cf59d7ce69dfabb4e55b4fd9      218.04         218.04  2.842171e-14
5   00048cc3ae777c65dbb7d2a0634bc1ea       34.59          34.59 -7.105427e-15
11  00063b381e2406b52ad429470734ebd5       57.98          57.98  7.105427e-15
13  0008288aa423d2a3f00fcb17cd7d8719      126.54         126.54 -1.421085e-14
14  0009792311464db532ff765bf7b182ae      127.55         127.55  1.421085e-14
17  000c3e6612759851cc3cbb4b83257986      112.71         112.71  1.421085e-14
20  000e906b789b55f64edcb1f84030f90d       33.84          33.84 -7.105427e-15
27  00130c0eee84a3d909e75bc08c5c3ca1       35.84          35.84 -7.105427e-15
31  00143d0f86d6fbd9f9b38ab440ac16f5      109.29         109.29 -1.421085e-14
35  0016dfedd97fc2950e388d2971d718c7       70.55          70.55 -1.421085e-14

In [322]:
order_payment_check["difference"].round(2).ne(0).sum()

np.int64(576)

In [323]:
order_payment_check.loc[
    order_payment_check["difference"].round(2).ne(0),
    ["order_id", "item_total", "payment_value", "difference"]
].head(10)

                              order_id  item_total  payment_value  difference
134   005d9a5423d47281ac463a968b3936fb      145.25         145.26       -0.01
165   00789ce015e7e5791c7914f32bb4fad4      168.83         190.81      -21.98
525   016726239765c18f66826453f39c64e3      235.13         265.77      -30.64
724   01e51b7c3025655646143d09b911e1d7       33.10          35.02       -1.92
965   028aa7c930356788f861ed1b7f984819       57.53          62.94       -5.41
1123  02f4dd90ba0feb8ec394cac05862d2b5      130.96         141.65      -10.69
1233  033ccfbdfc4d29677b7e1e6df3a82820       59.96          69.26       -9.30
1248  0345ba423eed2b009e0e407b19c422e4       77.75          83.17       -5.42
1418  03b218d39c422c250f389120c531b61f       50.24          58.03       -7.79
1789  04993613aee4046caf92ea17b316dcfb      524.32         524.28        0.04

In [324]:
order_items.loc[
    order_items["order_id"] == "00789ce015e7e5791c7914f32bb4fad4",
    ["order_id", "order_item_id", "price", "freight_value", "item_total"]
]

,order_id,order_item_id,price,freight_value,item_total
185,00789ce015e7e5791c7914f32bb4fad4,1,154.0,14.83,168.83

In [325]:
order_payments.loc[
    order_payments["order_id"] == "00789ce015e7e5791c7914f32bb4fad4"
]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
97517,00789ce015e7e5791c7914f32bb4fad4,1,credit_card,10,190.81

In [326]:
order_reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [327]:
order_reviews["review_score"].value_counts().sort_index()

# in this code we count various review value and no of rows in it

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [328]:
order_reviews.duplicated().sum()

np.int64(0)

In [329]:
order_reviews["order_id"].value_counts().value_counts().sort_index()

# this tell us no of reviews  order with 1 review, no of order with 2 review and soon 
# first value count tell how many times each order appear in the review table, - if it appear 3 times obviously it have 3 review
# then second value count - checks how many orders have 3 reviews

count
1    98126
2      543
3        4
Name: count, dtype: int64

In [330]:
order_reviews["order_id"].value_counts().loc[lambda x: x == 3]

order_id
c88b1d1b157a9999ce368f218a407141    3
df56136b8031ecd28e200bb18e6ddb2e    3
03c939fd7fd3b38f8485a0f95798f1f6    3
8e17072ec97ce29f0e1f111e598b0c85    3
Name: count, dtype: int64

In [331]:
order_reviews.loc[
    order_reviews["order_id"].isin([
        "03c939fd7fd3b38f8485a0f95798f1f6",
        "8e17072ec97ce29f0e1f111e598b0c85",
        "c88b1d1b157a9999ce368f218a407141",
        "df56136b8031ecd28e200bb18e6ddb2e"
    ]),
    ["order_id", "review_id", "review_score",
     "review_comment_title", "review_comment_message",
     "review_creation_date", "review_answer_timestamp"]
]

,order_id,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
1985,c88b1d1b157a9999ce368f218a407141,ffb8cff872a625632ac983eb1f88843c,3,NaN,NaN,2017-07-22,2017-07-26 13:41:07
2952,df56136b8031ecd28e200bb18e6ddb2e,c444278834184f72b1484dfe47de7f97,5,NaN,NaN,2017-02-08,2017-02-14 13:58:48
8273,03c939fd7fd3b38f8485a0f95798f1f6,b04ed893318da5b863e878cd3d0511df,3,NaN,Um ponto negativo que achei foi a cobrança de ...,2018-03-20,2018-03-21 02:28:23
13982,df56136b8031ecd28e200bb18e6ddb2e,72a1098d5b410ae50fbc0509d26daeb9,5,NaN,NaN,2017-02-07,2017-02-10 10:46:09
44694,8e17072ec97ce29f0e1f111e598b0c85,67c2557eb0bd72e3ece1e03477c9dff5,1,NaN,Entregou o produto errado.,2018-04-07,2018-04-08 22:48:27
51527,03c939fd7fd3b38f8485a0f95798f1f6,f4bb9d6dd4fb6dcc2298f0e7b17b8e1e,4,NaN,NaN,2018-03-29,2018-03-30 00:29:09
62728,df56136b8031ecd28e200bb18e6ddb2e,44f3e54834d23c5570c1d010824d4d59,5,NaN,NaN,2017-02-09,2017-02-09 09:07:28
64510,8e17072ec97ce29f0e1f111e598b0c85,2d6ac45f859465b5c185274a1c929637,1,NaN,Comprei 3 unidades do produto vieram 2 unidade...,2018-04-07,2018-04-07 21:13:05
69438,03c939fd7fd3b38f8485a0f95798f1f6,405eb2ea45e1dbe2662541ae5b47e2aa,3,NaN,Seria ótimo se tivesem entregue os 3 (três) pe...,2018-03-06,2018-03-06 19:50:32
82525,c88b1d1b157a9999ce368f218a407141,202b5f44d09cd3cfc0d6bd12f01b044c,5,NaN,NaN,2017-07-22,2017-07-26 13:40:22
89360,c88b1d1b157a9999ce368f218a407141,fb96ea2ef8cce1c888f4d45c8e22b793,5,NaN,NaN,2017-07-21,2017-07-26 13:45:15
92300,8e17072ec97ce29f0e1f111e598b0c85,6e4c4086d9611ae4cc0cc65a262751fe,1,NaN,"Embora tenha entregue dentro do prazo, não env...",2018-04-14,2018-04-16 11:37:31

In [332]:
order_reviews[
    ["review_comment_title", "review_comment_message"]
].isnull().all(axis=1).sum()

np.int64(56518)

In [333]:
order_reviews[
    ["review_comment_title", "review_comment_message"]
].isnull().sum(axis=1).value_counts()

2    56518
1    32867
0     9839
Name: count, dtype: int64

In [334]:
review_order_check = order_reviews.merge(
    orders[["order_id", "order_purchase_timestamp"]],
    on="order_id",
    how="left"
)

In [335]:
(review_order_check["review_creation_date"] < review_order_check["order_purchase_timestamp"].dt.date).sum()

np.int64(64)

In [336]:
review_order_check.loc[
    review_order_check["review_creation_date"] <
    review_order_check["order_purchase_timestamp"].dt.date,
    [
        "order_id",
        "order_purchase_timestamp",
        "review_creation_date",
        "review_answer_timestamp"
    ]
].head(10)

,order_id,order_purchase_timestamp,review_creation_date,review_answer_timestamp
5293,4d59cc2a2e7bb6c0a851725f5888a9b5,2018-09-06 14:50:07,2018-07-31,2018-07-31 23:11:57
5503,e5215415bb6f76fe3b7cb68103a0d1c0,2016-10-22 08:25:27,2016-10-09,2016-10-11 14:31:29
8404,7813842ae95e8c497fc0233232ae815a,2018-08-17 20:06:36,2018-08-03,2018-08-06 00:09:52
8486,392ed9afd714e3c74767d0c4d3e3f477,2018-09-29 09:13:03,2018-08-26,2018-08-28 01:26:38
10412,0fb9645c128ac84788798f0129496ca7,2018-08-21 10:15:51,2018-08-04,2018-08-05 17:21:32
10445,2bb02fdf5637a68cd5d13c78c37c3376,2018-08-09 10:55:10,2018-08-01,2018-08-04 09:51:18
13454,f81e71dd7c044a9ee7c1d6e37d68d64f,2018-08-15 08:34:42,2018-07-21,2018-07-24 00:09:40
13872,a89abace0dcc01eeb267a9660b5ac126,2018-09-06 18:45:47,2018-07-31,2018-08-02 15:11:49
18311,b102b42cde7719ae4b7c0163cf4d7dbe,2018-08-29 10:15:27,2018-08-12,2018-08-12 14:44:26
18897,afed0d88ec7753e7be8744bb66e860d1,2018-08-02 15:23:07,2018-07-28,2018-07-29 11:14:13

In [337]:
(
    review_order_check["review_answer_timestamp"].dt.date
    < review_order_check["review_creation_date"]
).sum()

np.int64(38)

In [338]:
review_order_check.loc[
    review_order_check["review_answer_timestamp"].dt.date <
    review_order_check["review_creation_date"],
    [
        "order_id",
        "review_creation_date",
        "review_answer_timestamp",
        "order_purchase_timestamp"
    ]
].head(10)

,order_id,review_creation_date,review_answer_timestamp,order_purchase_timestamp
444,c0f3e5b46a6f8a899bb3a9de4afd5525,2017-10-15 01:00:00,2017-10-15 22:24:11,2017-09-24 13:37:42
8087,75cc0defdf90cda65066ce0ac171e2ab,2017-10-15 01:00:00,2017-10-15 17:53:22,2017-10-08 16:49:21
9123,0c021596b865eb54c02ad64bf7d55aea,2017-10-15 01:00:00,2017-10-15 20:01:52,2017-10-04 00:03:23
9825,3538ead6f9b48a09ea5f84cce99614f1,2017-10-15 01:00:00,2017-10-15 23:20:37,2017-10-07 22:33:52
14229,a3cb021819344fef213fb8b1bf340a8c,2017-10-15 01:00:00,2017-10-15 16:45:55,2017-09-08 17:33:58
15325,afc5e76e5cc169a08cec884d98173efb,2017-10-15 01:00:00,2017-10-15 15:30:44,2017-10-01 20:48:40
19539,b6659c782155d09b529dc57d587fd87d,2017-10-15 01:00:00,2017-10-15 19:21:06,2017-09-30 21:55:40
28075,b8b9d7046c083150cb5360b83a8ebb51,2016-10-16 01:00:00,2016-10-16 15:45:11,2016-10-06 12:51:54
34491,d798a6f2eef74e8cd33a5c79db6a316c,2017-10-15 01:00:00,2017-10-15 21:05:48,2017-10-06 22:18:54
36242,2992972c3d2aff1e457a1b320c51e278,2017-10-15 01:00:00,2017-10-15 17:30:32,2017-10-07 21:25:21

In [339]:
review_order_check[
    ["review_creation_date", "review_answer_timestamp"]
].dtypes

review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

In [340]:
(
    review_order_check["review_answer_timestamp"].dt.normalize()
    <
    review_order_check["review_creation_date"].dt.normalize()
).sum()

np.int64(0)

In [341]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [342]:
sellers.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='str')

In [343]:
sellers["seller_id"].duplicated().sum()

np.int64(0)

In [344]:
sellers["seller_state"].value_counts()

seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
CE      13
PE       9
PB       6
RN       5
MS       5
MT       4
RO       2
SE       2
AC       1
PI       1
MA       1
AM       1
PA       1
Name: count, dtype: int64

In [345]:
sellers["seller_zip_code_prefix"].describe()

count     3095.000000
mean     32291.059451
std      32713.453830
min       1001.000000
25%       7093.500000
50%      14940.000000
75%      64552.500000
max      99730.000000
Name: seller_zip_code_prefix, dtype: float64

In [346]:
(sellers["seller_zip_code_prefix"].astype(str).str.len() != 5).sum()

np.int64(1027)

In [347]:
sellers.loc[
    sellers["seller_zip_code_prefix"].astype(str).str.len() != 5,
    "seller_zip_code_prefix"
].head(20)

3     4195
8     1529
12    1222
13    5372
19    5138
22    4156
27    9850
28    4857
31    2261
33    3562
36    7241
38    3445
39    4133
49    9251
50    4705
51    6144
60    6544
61    9121
63    6056
65    5741
Name: seller_zip_code_prefix, dtype: int64

In [348]:
sellers["seller_zip_code_prefix"] = (
    sellers["seller_zip_code_prefix"]
    .astype(str)
    .str.zfill(5)
)

In [349]:
(sellers["seller_zip_code_prefix"].str.len() != 5).sum()

np.int64(0)

In [350]:
category_translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [351]:
category_translation.columns

Index(['product_category_name', 'product_category_name_english'], dtype='str')

In [352]:
category_translation["product_category_name"].duplicated().sum()

np.int64(0)

In [353]:
category_translation["product_category_name_english"].duplicated().sum()

np.int64(0)

In [354]:
(
    category_translation["product_category_name"].str.strip().eq("").sum(),
    category_translation["product_category_name_english"].str.strip().eq("").sum()
)

(np.int64(0), np.int64(0))

In [355]:
sellers["seller_zip_code_prefix"].head(10)

0    13023
1    13844
2    20031
3    04195
4    12914
5    20920
6    55325
7    16304
8    01529
9    80310
Name: seller_zip_code_prefix, dtype: str

In [356]:
sellers.to_csv(
    "../data/processed/sellers.csv",
    index=False
)

In [357]:
pd.read_csv("../data/processed/sellers.csv").head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [358]:
pd.read_csv(
    "../data/processed/sellers.csv",
    dtype={"seller_zip_code_prefix": str}
).iloc[3]

seller_id                 c0f3eea2e14555b6faeea3dd58c1b1c3
seller_zip_code_prefix                               04195
seller_city                                      sao paulo
seller_state                                            SP
Name: 3, dtype: str

In [359]:
category_translation.to_csv(
    "../data/processed/product_category_name_translation.csv",
    index=False
)

In [360]:
order_reviews.dtypes

review_id                             str
order_id                              str
review_score                        int64
review_comment_title                  str
review_comment_message                str
review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

In [363]:
order_reviews.to_csv(
    "../data/processed/order_reviews.csv",
    index = False
)

In [364]:
order_payments["payment_value"].dtype

dtype('float64')

In [367]:
order_payments.to_csv(
    "../data/processed/order_payments.csv",
    index=False
)

In [366]:
order_items["shipping_limit_date"].dtype

dtype('<M8[us]')

In [368]:
order_items.to_csv(
    "../data/processed/order_items.csv",
    index=False
)

In [369]:
orders.to_csv(
    "../data/processed/orders.csv",
    index=False
)

In [370]:
customers.to_csv(
    "../data/processed/customers.csv",
    index=False
)

In [371]:
products.to_csv(
    "../data/processed/products.csv",
    index=False
)

In [372]:
geolocation.to_csv(
    "../data/processed/geolocation.csv",
    index=False
)

In [373]:
import os

os.listdir("../data/processed")

['customers.csv',
 'geolocation.csv',
 'orders.csv',
 'order_items.csv',
 'order_payments.csv',
 'order_reviews.csv',
 'products.csv',
 'product_category_name_translation.csv',
 'sellers.csv']